language: node_js
script:
- npm run precommit
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: okZSW4Lj/ppXNK0v3O+3pkM4j+uoTlMtCADz9jleti4484E0ojwXbLPSLl4GgZMxSTC+FN3g054czqGs9O40lXHG5Xi5PKVDULdBZ5sZQaKaPRPodqQciDEUqLUOt7ZDtwjImpkp7WU/1YLYzFduEeHwr4wEFlEh14+MbmZT6VbzfgoKpx0PYcVHkQapifJWQD+uhfFvENmTSCYeZVSuydkXCkcvcDFAeQ7UKwnkIJB6fb4LZqHqkR26YoMFRciIgFYrTyS1PzkfS+9FIiY2wAHfSfG/6OTd0EI7uO40kNvYW//Nn8hpiuMNFvlqhZ/wPTfIFkaap1BiuBa/7Sya7bZocwJ84Z2jXHQak2W7kS7CXGWeoAovD64a88nOAONY7ZLsaPyi19A3fYR7eyJCa/zoG1C4ljQRe64QPjEkwyayso8+HjOUmeLdcOaGeAZmadQZrvEqUVCOlLagwS43qIf59UtRKUziJf3u4xQkyDoGYDWvVQ2v+n8rA5Z3cAi3EQ0KwSA/ZVXlCsQbaXXgPBvtpxGnpYxOs9y/vwuwMGDOok2WlMaTSNNfm+S9jLX9wDKxarKyKhrerKg5dt1s45J6t+KYJwEIBPOpH25qqX4xzt9AflBcgl4suc/IfR8dueyXycIoT65TAKKOGrHpV1iQY5V4VmAYd76F3sGVLLc=
  app: twlevelup-syd-2017-s2-green
  on:
    repo: twlevelup/SydBuild2017S2_Green
