language: node_js
script:
- npm run precommit
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: AVCMUkUHyzR3mb3lHSbM5WDehcv8Hxynj24cZHfKoJJYD9KIunk5XOVJNrw7r23AtFd3ypRtMlLCLfCajlXjXN58WvABeT674JhLvbUMyiW1kMUY87Y8dUmm1mung71nfXo3/qSR6Wg4mIiNYfICwglrA7xumkbaiLiawlqGn6r49QZbKgXNO6yKGrBsY8q8dvexBmi4y24Cz+zjpwY3cnj1MaGFIQplMT21fmxFb+tdHXgaeG3DQeZv8EX6+2wTIriy+MZSYZHQFwaEtEQAE9dDQ+dnV5cCmOgHGdxy1UOVrWmqRJ5U73sIyNAyVkXPL7v1zr42pvb0eELG3Bvq0tIjDi8KZD7xezvlDmme8PEQCP02e26xpI8xcGBmj8gy3Cn2i3URBoJLHRZpewxM/oacDxOaJSjSJBxPpFEcYWlM0r/FvpxkCMyJ7B426D0KIQw4ThNzg61ZWmhJkbq9BVU6yJTVaCXjI8Z5wZ4H9/FDXVSKAkgtoXjf8rKQ2SWr9a5IC8i79QAkaoWJEMPVV1arKiF/dLgMDRw04y9YUxbHbrIO8uD35UCsLglR0gbUP7Ur5mjcWZ3BxbqmSpX62Sn1V3GkVRF1sgk9jihQTFqXBYUxAAx+mq/SE4vQOg150e19/kNBS6o6xjLWV35fmsdWjfi1KcJnJdDuD3lZVdc=
  app: twlevelup-syd-2017-s2-green
  on:
    repo: twlevelup/SydBuild2017S2_Green
notifications:
  slack:
    secure: clr0JRQFRg71L3POIoWDPqU6Zm9JXayKY0s2lMhYeJsXiPxGoo77kQn5gnLq6R5v70ZeUMU3cPcc67Ghn8AvUw6ykPwJLM0LoZxKSl91/ozOKw4+zrXHmVdP24iCqly8brVv38PTHGQaYXpeNS9vD51vUEKPHDOwMDDWNtLOhyCx53EN1RElPLsip44nTRrDb53lcDCKw786ePe7E7HE8YwXLOAlAEPmKcTLxTpqceweObRrqdRL8/hsuiO73p3vriPM+G5/nbwzhkoH6HkudRbLSovjVon0vBtNneDztKtWOT6pmrJuPxfrY/zepWTymJVUR0dg1cN4AuobTYBpGjJcZAP6mH3phbWwZtszTu+EsWw40g6XfWw25j8u2ISP8EPLPDEH3CUbuBl70MKu2kZ193/N5dkSxjsDMRyUj/CNvLfxCHl2ZwBw/+I54gNPzxZ8yGshkLPMXm4IU38OtIOzXyYX6B1Vg9ojyJN3VeL9NtMt2UHb63LEdWWnq7ZbT9uTjG3KenmcGzJ9gMDZHSTpw0LRgrz1WetcryjC45sO3huQMMubYRWzlkKUSivNA1mAQ3wqckNNC4JwdqRO20tpOS/gyg66Ifhlwg0kfcR8dzRnQ5wa/k4QkpwthmqhqhYY+gbTRKo1IbmgqbPdsnVRsG1XsZ4gf3TzGweGIb0=
