version: 2
jobs:
  build:
    docker:
      # Circle CI does not currently have a node 8 Image
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:7.10.0
    steps:
      - checkout
      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run test:ci
  lint:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run lint
  deploy:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: bash .circleci/setup-heroku.sh
        - add_ssh_keys:
            fingerprints:
              - "8f:95:30:a9:c5:a5:f7:dc:85:aa:e7:5f:45:52:91:11"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku run python manage.py deploy
              heroku restart
            fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
